FROM serversideup/php:8.3-fpm-apache-debian 

USER root 
ARG SUITEVERSION=8-9-1
RUN apt-get update && apt-get install -y mariadb-client wget vim iputils-ping curl ca-certificates gnupg lsb-release \
    && curl -sL https://aka.ms/InstallAzureCLIDeb | bash \
    && rm -rf /var/lib/apt/lists/*
RUN install-php-extensions gd zip mysqli opcache bcmath intl curl xml json mbstring pdo pdo_mysql openssl soap tokenizer zip imap ldap 

WORKDIR /var/www/html 

ADD https://suitecrm.com/download/166/suite89/565627/suitecrm-$SUITEVERSION.zip  /var/www/html 
RUN unzip suitecrm-$SUITEVERSION.zip && rm suitecrm-$SUITEVERSION.zip
COPY --chown=www-data:www-data SuiteCRM/extensions/Ofqual /var/www/html/extensions/Ofqual/ 
COPY --chown=www-data:www-data SuiteCRM/public/legacy/custom/. /var/www/html/public/legacy/custom
COPY --chown=www-data:www-data SuiteCRM/public/legacy/modules/. /var/www/html/public/legacy/modules

COPY scripts/startup.sh /var/www/scripts/startup.sh
# COPY scripts/99-mountperms.sh /etc/entrypoint.d/99-mountperms.sh
COPY --chown=www-data:www-data scripts/repairrebuild.sh /var/www/html/repairrebuild.sh
COPY --chown=www-data:www-data scripts/htaccess /var/www/html/public/legacy/.htaccess
RUN chmod +x /var/www/html/repairrebuild.sh

COPY scripts/s6/. /etc/s6-overlay/s6-rc.d/
RUN chmod +x /var/www/scripts/startup.sh 

COPY --chown=www-data:www-data SuiteCRM/public/legacy/config-interim.php /var/www/html/public/legacy/config-interim.php

RUN find /var/www/html/. -type d -not -perm 2755 -exec chmod 2755 {} \; && \ 
    find /var/www/html/. -type f -not -perm 0644 -exec chmod 0644 {} \; && \ 
    find /var/www/html/. ! -user www-data -exec chown www-data:www-data {} \;  
RUN chmod +x /var/www/html/bin/console

USER www-data